@trifork_HostAddress = http://localhost:5174


### Add Player 1
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Ole Odder",
  "initials": "OO",
  "handicap": 7
}

### Add Player 2
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Jens Lyn",
  "initials": "JK",
  "handicap": 2
}

### Add Player 3
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Jeppe Gade Nielsen",
  "initials": "jgn"
}

### Add Player 4
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Nella Freinhofer",
  "initials": "NF",
  "handicap": 14
}

### Update Player 2 initials
PATCH {{trifork_HostAddress}}/foosball/players/57ad75ea-e5f4-4876-a0c5-9acb5c882011
Content-Type: application/json

{
  "initials": "JL"
}

### Update Player 2 initials but its way too long
PATCH {{trifork_HostAddress}}/foosball/players/57ad75ea-e5f4-4876-a0c5-9acb5c882011
Content-Type: application/json

{
  "initials": "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ"
}

### Delete Player
DELETE {{trifork_HostAddress}}/foosball/players/b1227506-39d5-4ac2-8194-35a811b6b56b

### List Players
GET {{trifork_HostAddress}}/foosball/players/

### Search Players
GET {{trifork_HostAddress}}/foosball/players/search/Je

### Add Match
POST {{trifork_HostAddress}}/foosball/match
Content-Type: application/json

{
  "team1Player1": "d8c683d1-a074-400c-a0b7-fb72a080caa1",
  "team1Player2": "874681cd-47bd-460b-b8dc-607757a4a17b",
  "team2Player1": "f60ea8f6-ffc1-4232-bb6e-8e20d7078b6b",
  "team2Player2": "9c9c32a9-ab84-4922-b6f7-039cc3902520"
}

### Get Match
GET {{trifork_HostAddress}}/foosball/match/eb794479-b391-4a18-a550-3e54dc2b734d

### Update Match
PATCH {{trifork_HostAddress}}/foosball/match/eb794479-b391-4a18-a550-3e54dc2b734d
Content-Type: application/json

{
  "matchId": "eb794479-b391-4a18-a550-3e54dc2b734d",
  "winningTeam": 2
}

