@trifork_HostAddress = http://localhost:5174


### Add Player 1
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Ole Odder",
  "initials": "OO",
  "handicap": 7
}

### Add Player 2
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Jens Lyn",
  "initials": "JK",
  "handicap": 2
}

### Add Player 3
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Jeppe Gade Nielsen",
  "initials": "jgn"
}

### Add Player 4
POST {{trifork_HostAddress}}/foosball/players
Content-Type: application/json

{
  "name": "Nella Freinhofer",
  "initials": "NF",
  "handicap": 14
}

### Update Player 2 initials
PATCH {{trifork_HostAddress}}/foosball/players/f98c5545-7412-4770-b076-ad3fd56f5960
Content-Type: application/json

{
  "initials": "JL"
}

### Update Player 2 initials but its way too long
PATCH {{trifork_HostAddress}}/foosball/players/f98c5545-7412-4770-b076-ad3fd56f5960
Content-Type: application/json

{
  "initials": "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ"
}

### Delete Player
DELETE {{trifork_HostAddress}}/foosball/players/b1227506-39d5-4ac2-8194-35a811b6b56b

### List Players
GET {{trifork_HostAddress}}/foosball/players/

### Search Players
GET {{trifork_HostAddress}}/foosball/players/search/Je

### Add Match
POST {{trifork_HostAddress}}/foosball/match
Content-Type: application/json

{
  "team1Player1": "a34baeea-5eb4-4839-add3-518e3f6fbcc3",
  "team1Player2": "fefa91e2-b8ab-4dd6-bb62-400b6ffceca7",
  "team2Player1": "52a327c0-a305-41fe-ae51-c398af031ec0",
  "team2Player2": "b446c89e-6e5a-4105-8916-ad3eba8c3b8d"
}

### Get Match
GET {{trifork_HostAddress}}/foosball/match/376430ea-77a7-4c32-b5fb-40121feb99f2

### Update Match
PATCH {{trifork_HostAddress}}/foosball/match/376430ea-77a7-4c32-b5fb-40121feb99f2
Content-Type: application/json

{
  "matchId": "eb794479-b391-4a18-a550-3e54dc2b734d",
  "winningTeam": 2
}

